apiVersion: apps/v1
kind: Deployment
metadata:
  name: basic-service
  labels:
    app: basic-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: basic-service
  template:
    metadata:
      labels:
        app: basic-service
    spec:
      containers:
        - name: basic-service
          image: saihu-acr-registry-vpc.cn-hongkong.cr.aliyuncs.com/scm-prod/basic-service:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 4004
            - containerPort: 5004
          envFrom:
            - secretRef:
                name: basic-service-secret
