apiVersion: apps/v1
kind: Deployment
metadata:
  name: order-service
  labels:
    app: order-service
spec:
  replicas: 3
  selector:
    matchLabels:
      app: order-service
  template:
    metadata:
      labels:
        app: order-service
    spec:
      containers:
        - name: order-service
          image: saihu-acr-registry-vpc.cn-hongkong.cr.aliyuncs.com/scm-prod/order-service:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 4001
            - containerPort: 5001
          envFrom:
            - secretRef:
                name: order-service-secret
