# --- 1. external HTTP /healthz ---
apiVersion: v1
kind: Service
metadata:
  name: procurement-service
spec:
  type: ClusterIP
  selector:
    app: procurement-service
  ports:
    - name: http
      port: 80
      targetPort: 4082
---
# --- 2. in-cluster raw TCP ---
apiVersion: v1
kind: Service
metadata:
  name: procurement-service-tcp
spec:
  clusterIP: None
  selector:
    app: procurement-service
  ports:
    - name: tcp-micro
      port: 5082
      targetPort: 5082
